# Configuration file to use as input for functions of the NLP module.
# -------------------------------------------------------------------

#---------#
# GLOBALS #
#---------#

# Path to the feather file containing the Italian common crowl + wiki model
# embeddings
define: &model_path /data/nlp/models/cc.it.300.feather
# Path to the original human generated colour and emotion wheel coordinates
define: &path_col_wheel '/data/nlp/wheels/it/sighted/colorwheel_coords.csv'
define: &path_em_wheel '/data/nlp/wheels/it/sighted/emotionwheel_coords.csv'
# Path to the csv file holding the coordinates of colors and emotions in the control space
define: &path2control  '/Data/Osgood/Coordinates/centroids_control.csv'
# Osgood representative words:
define: &valence [positivo, negativo]
define: &arousal [attivo, tranquillo]
# Mapping between english and italian color and emotion words
define: &emotion_words [sorpreso, entusiasta, sereno, allegro, soddisfatto,
  calmo, stanco, annoiato, depresso, triste, frustrato, spaventato, arrabbiato,
  stressato, stupito, assonnato, allarmato, disgustato]
define: &color_words [verde, arancione, giallo, blu, viola, rosso]


#-----------------------------------------------------------------------------#
# osgood.get_wheel()
#-----------------------------------------------------------------------------#
# Get coordinates of colors and emotionsin the Osgood dimensions
get_wheel:
  # Path to the feather file containing the english wiki-news-300d-1M model
  # embeddings
  model: *model_path
  # Osgood representative words
  valence: *valence
  arousal: *arousal
  # List with the color words to use int he analysis
  color_words: *color_words
  emotion_words: *emotion_words
  # Where to save the table with the coordinates
  save_coords: /data/nlp/coordinates/osgood_coords_it.csv
  # Location of the neighbours used to compute the centroids
  neighbours: /data/nlp/neighbours/neighbours_osgood_it.pkl 

#-----------------------------------------------------------------------------#
# osgood.get_wheel()
#-----------------------------------------------------------------------------#
# Get coordinates of colors and emotionsin the control dimensions
get_control_wheel:
  # Path to the feather file containing the english wiki-news-300d-1M model
  # embeddings
  model: *model_path
  # Osgood representative words
  valence: ['Nord', 'Sud']
  arousal: ['Est', 'Ovest']
  # List with the color words to use in the analysis
  color_words: *color_words
  emotion_words: *emotion_words
  # Where to save the table with the coordinates
  save_coords: /data/nlp/coordinates/control_coords_it.csv
  # Location of the neighbours used to compute the centroids
  neighbours: /data/nlp/neighbours/neighbours_control_it.pkl 
    
#-----------------------------------------------------------------------------#
# osgood.control_rdm()
#-----------------------------------------------------------------------------#
# Generate RDMs for the control conditions
control_rdm:
  # Path the .csv file with the coordinates of color and emotion words in the
  # control spaces computed with debiaswe method
  path2control: /data/nlp/coordinates/control_coords_it.csv
  # Path to the model
  model_path: *model_path
  # List with the color and emotions words to use int he analysis
  color_words: *color_words
  emotion_words: *emotion_words
  # Path to the folder where to save the control matrices
  save_control: '/data/nlp/RDMs/it/sighted/'

#-----------------------------------------------------------------------------#
# osgood.osgood_rdm()                                                          #
#-----------------------------------------------------------------------------#
rdm_difference:
  # Path to the human generated emotion wheel
  path_em_wheel: *path_em_wheel
  # Path to the human generated colour wheel
  path_col_wheel: *path_col_wheel
  # Path to the folder with the control RDMs
  path2control_rdm: /data/nlp/RDMs/it/
  # List with the color words to use int he analysis
  color_words: *color_words
  emotion_words: *emotion_words
  # Path to the coordinates in osgoodspace of colors and emotions
  path_centroids: '/data/nlp/coordinates/osgood_coords_it.csv'
  # Where to save the tables with correlations and p-values (folder)
  path_results: /data/nlp/correlations/it/sighted/


#-----------------------------------------------------------------------------#
# osgood.coloremotion_associate()
#-----------------------------------------------------------------------------#
coloremotion_associate:
  # Where to save the mean across subjects of color-emotion associations
  human_associations: /data/nlp/associations/ColorEmotionMean_sighted.csv
  # List with the color and emotion words to use in the analysis
  color_words: *color_words
  emotion_words: *emotion_words
  # Path to the coordinates of color and emotion words the osgood dimensions 
  path_centroids: /data/nlp/coordinates/osgood_coords_it.csv
  # Where to save the results of the correlation (coefficient and p-value)
  corr_save1: /data/nlp/correlations/it/sighted/osgoodspace1.csv
  corr_save2: /data/nlp/correlations/it/sighted/osgoodspace2.csv
  # Path to the feather file containing the english wiki-news-300d-1M model
  # embeddings
  model_path: *model_path
  # Path to the csv file holding the coordinates of colors and emotions in the
  # control space
  path2control: /data/nlp/coordinates/control_coords_it.csv
