# Configuration file to use as input for functions of the NLP module.
# -------------------------------------------------------------------

#---------#
# GLOBALS #
#---------#

# Path to the feather file containing the Italian common crowl + wiki model
# embeddings
define: &model_path /data/nlp/models/cc.it.300.feather
# Path to the original human generated colour and emotion wheel coordinates
define: &path_col_wheel '/data/nlp/wheels/colorwheel_coords.csv'
define: &path_em_wheel '/data/nlp/wheels/emotionwheel_coords.csv'
# Path to the csv file holding the coordinates of colors and emotions in the control space
define: &path2control  '/Data/Osgood/Coordinates/centroids_control.csv'
# Osgood representative words:
define: &valence [positivo, negativo]
define: &arousal [attivo, tranquillo]
# Path to the raw single subjects similarity matrices (.npy file) of the blind
# participants
define: &raw_emotions_blind /Data/Color_words/participantsColorTestingItalianBlind.npy
define: &raw_colors_blind /Data/Color_words/participantsEmotionTestingItalianBlind.npy
define: &raw_associate_blind /Data/Color_words/participantsEmotionColorAssociationTestingItalianBlind.npy
# Mapping between english and italian color and emotion words
define: &emotion_words [sorpreso, entusiasta, sereno, allegro, soddisfatto,
  calmo, stanco, annoiato, depresso, triste, frustrato, spaventato, arrabbiato,
  stressato, stupito, assonnato, allarmato, disgustato]
define: &color_words [verde, arancione, giallo, blu, viola, rosso]


#-----------------------------------------------------------------------------#
# osgood.get_wheel()
#-----------------------------------------------------------------------------#
# Get coordinates of colors and emotionsin the Osgood dimensions
get_wheel:
  # Path to the feather file containing the english wiki-news-300d-1M model
  # embeddings
  model: *model_path
  # Osgood representative words
  valence: *valence
  arousal: *arousal
  # List with the color words to use int he analysis
  color_words: *color_words
  emotion_words: *emotion_words
  # Where to save the table with the coordinates
  save_coords: /data/nlp/coordinates/osgood_coords_it.csv
  # Location of the neighbours used to compute the centroids
  neighbours: /data/nlp/neighbours/neighbours_osgood_it.pkl 



